"""Merge researched CSVs into one seed list, score it, and write review files.

Usage: python scripts/build_seed_list.py <csv> [<csv> ...]

Outputs (committed, so the seed list is versioned):
  leads/seed_list.csv         merged and deduped input rows
  leads/seed_list_scored.csv  every lead with score, reasons, and seed signals
  leads/top_drafts.md         the day-0 email for the top-ranked leads

Enrichment is not run here because it needs network access to each brand's
site; run ``leadgen enrich`` on a machine with open egress, then ``leadgen score``.
"""

from __future__ import annotations

import csv
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from leadgen.discover import OPTIONAL_COLUMNS, SIGNAL_COLUMNS, dedupe, import_csv  # noqa: E402
from leadgen.facility import load_facility  # noqa: E402
from leadgen.models import Lead  # noqa: E402
from leadgen.outreach import SenderIdentity, load_sequence, render_sequence  # noqa: E402
from leadgen.scoring import apply_score, load_weights  # noqa: E402

LEADS_DIR = Path("leads")
TOP_N = 15


def merge(paths: list[Path]) -> list[Lead]:
    """Import every CSV, report skips, and dedupe across files."""
    leads: list[Lead] = []
    for path in paths:
        report = import_csv(path, default_source=path.stem.replace("leads_", ""))
        print(f"{path.name}: loaded {len(report.leads)}, skipped {len(report.skipped)}")
        for row_number, reason in report.skipped:
            print(f"  row {row_number}: {reason}")
        leads.extend(report.leads)
    unique = dedupe(leads)
    print(f"merged {len(leads)} -> {len(unique)} unique")
    return unique


def write_seed_csv(leads: list[Lead], path: Path) -> None:
    columns = ["company", *OPTIONAL_COLUMNS, *SIGNAL_COLUMNS]
    with open(path, "w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=columns)
        writer.writeheader()
        for lead in leads:
            row = lead.model_dump(mode="json")
            signals = {name: ("true" if getattr(lead.signals, name) else "") for name in SIGNAL_COLUMNS}
            writer.writerow({**{c: row.get(c, "") for c in columns}, **signals})


def write_scored_csv(leads: list[Lead], path: Path) -> None:
    columns = ["score", "company", "website", "category", "segment", "contact_name", "contact_title",
               "city", "state", "source", "score_reasons", "notes"]
    with open(path, "w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=columns)
        writer.writeheader()
        for lead in leads:
            row = lead.model_dump(mode="json")
            row["score_reasons"] = "; ".join(lead.score_reasons)
            writer.writerow({c: row.get(c, "") for c in columns})


def write_top_drafts(leads: list[Lead], path: Path) -> None:
    facility = load_facility()
    template = load_sequence()
    sender = SenderIdentity(name="[Your name]", title="Partnerships")
    lines = ["# Day-0 drafts for the top-ranked seed leads", "",
             "Generated by `scripts/build_seed_list.py`. Edit the first line by hand where the evidence in `notes` gives something sharper.", ""]
    for lead in leads[:TOP_N]:
        first = render_sequence(lead, facility, sender, template)[0]
        lines += [f"## {lead.score} · {lead.company} ({lead.category.value}, {lead.segment.value})",
                  f"- Website: {lead.website or 'unknown'}",
                  f"- Evidence: {lead.notes or 'none recorded'}",
                  f"- Score reasons: {'; '.join(lead.score_reasons)}", "",
                  f"**Subject:** {first.subject}", "", "```", first.body, "```", ""]
    path.write_text("\n".join(lines), encoding="utf-8")


def main(argv: list[str]) -> int:
    paths = [Path(p) for p in argv]
    if not paths:
        print(__doc__)
        return 1
    LEADS_DIR.mkdir(exist_ok=True)
    leads = merge(paths)
    weights, facility = load_weights(), load_facility()
    for lead in leads:
        apply_score(lead, weights, facility)
    leads.sort(key=lambda l: (-l.score, l.company.lower()))
    write_seed_csv(leads, LEADS_DIR / "seed_list.csv")
    write_scored_csv(leads, LEADS_DIR / "seed_list_scored.csv")
    write_top_drafts(leads, LEADS_DIR / "top_drafts.md")
    buckets = {"55+": sum(l.score >= 55 for l in leads), "40-54": sum(40 <= l.score < 55 for l in leads), "<40": sum(l.score < 40 for l in leads)}
    print(f"scored {len(leads)} leads: {buckets}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
