"""Download a theme's Google Fonts (Latin subset, WOFF2) and write its self-hosted ``fonts.css``.

Usage: ``python scripts/fetch_theme_fonts.py THEME "Family:axes@ranges" [...]``.
Files land in ``site/themes/<theme>/fonts/``; ``fonts.css`` points at ``/fonts/<file>``,
where the build copies them. Run it once per theme and commit the results; the site
build never fetches anything. All Google Fonts used here are under the SIL Open Font License.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

import httpx

CSS_API = "https://fonts.googleapis.com/css2"
CHROME = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Safari/537.36"
LATIN_BLOCK = re.compile(r"/\* latin \*/\s*(@font-face\s*\{.*?\})", re.DOTALL)


def slug(text: str) -> str:
    """A file-name-safe lowercase form."""
    return re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")


def face_file(block: str) -> str:
    """A stable file name from a face's family, style, and weight."""
    family = re.search(r"font-family:\s*'([^']+)'", block).group(1)  # type: ignore[union-attr]
    style = re.search(r"font-style:\s*(\w+)", block).group(1)  # type: ignore[union-attr]
    weight = re.search(r"font-weight:\s*([\d ]+);", block).group(1).strip()  # type: ignore[union-attr]
    return f"{slug(family)}-{slug(weight)}{'-italic' if style == 'italic' else ''}.woff2"


def fetch(theme: str, families: list[str]) -> None:
    """Download every Latin face for the families and write fonts.css."""
    out = Path("site/themes") / theme / "fonts"
    out.mkdir(parents=True, exist_ok=True)
    rules: list[str] = []
    with httpx.Client(headers={"User-Agent": CHROME}, timeout=30) as client:
        for family in families:
            css = client.get(CSS_API, params={"family": family, "display": "swap"}).raise_for_status().text
            for block in LATIN_BLOCK.findall(css):
                url = re.search(r"url\((https://[^)]+\.woff2)\)", block).group(1)  # type: ignore[union-attr]
                name = face_file(block)
                (out / name).write_bytes(client.get(url).raise_for_status().content)
                rules.append(re.sub(r"src:\s*url\([^)]+\)", f'src: url("/fonts/{name}")', block))
    header = f"/* {theme}: self-hosted Latin-subset fonts (SIL Open Font License). Generated by scripts/fetch_theme_fonts.py. */\n"
    (out.parent / "fonts.css").write_text(header + "\n".join(rules) + "\n", encoding="utf-8")
    print(f"{theme}: {len(rules)} faces")


if __name__ == "__main__":
    fetch(sys.argv[1], sys.argv[2:])
